"""
DistillationAgent — Cross-model self-distillation for ScholarFormer.

The key "mind-blowing" feature of ScholarMind V2:
    Phi-3 (teacher, 3.8B) → generates Q&A pairs → trains ScholarFormer (student, 122M)
    
This process repeats in cycles, with ScholarFormer generating new questions
and Phi-3 providing high-quality answers, allowing the smaller custom model 
to progressively approach the performance of the larger fine-tuned model.

Distillation loop:
    1. Phi-3 generates Q&A pairs from paper chunks
    2. ScholarFormer trains on these Q&A pairs (soft + hard targets)
    3. ScholarFormer generates new questions from its understanding
    4. Phi-3 answers those questions → new training data
    5. Repeat for N cycles
"""

import os
import json
import time
import logging
from datetime import datetime
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from scholarformer.config import ScholarFormerConfig
from scholarformer.model import ScholarFormerModel

logger = logging.getLogger(__name__)


# ==============================================================================
# Q&A Dataset for Distillation
# ==============================================================================

class DistillationDataset(Dataset):
    """Dataset of Q&A pairs generated by the teacher model."""
    
    def __init__(self, qa_pairs: List[Dict], tokenizer, max_length: int = 512):
        """
        Args:
            qa_pairs: List of {'question': str, 'answer': str, 'source': str}
            tokenizer: Tokenizer instance
            max_length: Maximum sequence length
        """
        self.samples = []
        
        for pair in qa_pairs:
            question = pair.get('question', '')
            answer = pair.get('answer', '')
            
            if not question or not answer:
                continue
            
            # Format as Q&A pair
            text = f"Question: {question}\n\nAnswer: {answer}"
            
            # Tokenize
            if hasattr(tokenizer, 'tokenizer'):
                encoded = tokenizer.tokenizer(
                    text, max_length=max_length,
                    truncation=True, return_tensors='pt'
                )
            else:
                encoded = tokenizer(
                    text, max_length=max_length,
                    truncation=True, return_tensors='pt'
                )
            
            input_ids = encoded['input_ids'].squeeze(0)
            
            self.samples.append({
                'input_ids': input_ids,
                'labels': input_ids.clone(),
            })
        
        logger.info(f"Distillation dataset: {len(self.samples)} Q&A pairs")
    
    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, idx):
        return self.samples[idx]


def distillation_collate_fn(batch):
    """Collate with padding for variable-length Q&A pairs."""
    max_len = max(item['input_ids'].shape[0] for item in batch)
    
    input_ids_list = []
    labels_list = []
    masks_list = []
    
    for item in batch:
        seq_len = item['input_ids'].shape[0]
        pad_len = max_len - seq_len
        
        input_ids_list.append(
            torch.cat([item['input_ids'], torch.zeros(pad_len, dtype=torch.long)])
        )
        labels_list.append(
            torch.cat([item['labels'], torch.full((pad_len,), -100, dtype=torch.long)])
        )
        masks_list.append(
            torch.cat([torch.ones(seq_len, dtype=torch.long),
                       torch.zeros(pad_len, dtype=torch.long)])
        )
    
    return {
        'input_ids': torch.stack(input_ids_list),
        'labels': torch.stack(labels_list),
        'attention_mask': torch.stack(masks_list),
    }


# ==============================================================================
# Distillation Agent
# ==============================================================================

class DistillationAgent:
    """
    Cross-model self-distillation: Phi-3 (teacher) → ScholarFormer (student).
    
    The distillation loop:
    1. Teacher generates Q&A pairs from paper content
    2. Student trains on these pairs
    3. Student generates new questions
    4. Teacher answers → new training data
    5. Repeat
    
    This demonstrates that a custom 122M model can approach the performance
    of a fine-tuned 3.8B model through iterative knowledge transfer.
    """
    
    def __init__(self, config: Dict, student_model: ScholarFormerModel,
                 student_tokenizer):
        """
        Args:
            config: Project configuration dict
            student_model: ScholarFormer model instance
            student_tokenizer: ScholarFormer tokenizer
        """
        self.config = config
        self.student = student_model
        self.student_tokenizer = student_tokenizer
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        
        # Teacher model will be loaded on demand
        self.teacher_model = None
        self.teacher_tokenizer = None
        
        # Distillation state
        self.cycle_history = []
        self.all_qa_pairs = []
        
        # Output
        self.output_dir = os.path.join(
            config.get('model_dir', './models'), 'distillation'
        )
        os.makedirs(self.output_dir, exist_ok=True)
        
        logger.info("DistillationAgent initialized")
    
    def _load_teacher(self):
        """
        Load the fine-tuned Phi-3 teacher model.
        Moves student to CPU first to free VRAM for the teacher.
        """
        if self.teacher_model is not None:
            return
        
        logger.info("Loading teacher model (Phi-3)...")
        logger.info("Moving student to CPU to free VRAM...")
        self.student = self.student.cpu()
        torch.cuda.empty_cache()
        
        from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
        
        base_model = self.config.get('base_model', 'microsoft/Phi-3-mini-4k-instruct')
        
        # Quantized loading for memory efficiency
        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_quant_type="nf4",
        )
        
        self.teacher_model = AutoModelForCausalLM.from_pretrained(
            base_model,
            quantization_config=quantization_config,
            device_map={"": 0},  # Force all to GPU 0
            trust_remote_code=True,
            token=os.environ.get('HF_TOKEN'),
            torch_dtype=torch.float16,
        )
        
        # Try loading fine-tuned adapter
        model_dir = self.config.get('model_dir', './models')
        adapter_dirs = [d for d in os.listdir(model_dir) 
                       if d.startswith('fine_tuned_') and os.path.isdir(os.path.join(model_dir, d))]
        
        if adapter_dirs:
            latest_adapter = sorted(adapter_dirs)[-1]
            adapter_path = os.path.join(model_dir, latest_adapter)
            try:
                from peft import PeftModel
                self.teacher_model = PeftModel.from_pretrained(
                    self.teacher_model, adapter_path
                )
                logger.info(f"Loaded fine-tuned adapter: {latest_adapter}")
            except Exception as e:
                logger.warning(f"Could not load adapter: {e}, using base Phi-3")
        
        self.teacher_tokenizer = AutoTokenizer.from_pretrained(
            base_model, trust_remote_code=True,
            token=os.environ.get('HF_TOKEN')
        )
        if self.teacher_tokenizer.pad_token is None:
            self.teacher_tokenizer.pad_token = self.teacher_tokenizer.eos_token
        
        self.teacher_model.eval()
        logger.info("Teacher model loaded and ready")
    
    def _swap_to_student(self):
        """Move teacher to CPU and student to GPU for training."""
        if self.teacher_model is not None:
            # Delete teacher to free VRAM
            del self.teacher_model
            self.teacher_model = None
            torch.cuda.empty_cache()
            logger.info("Teacher unloaded from GPU")
        
        self.student = self.student.to(self.device)
        logger.info("Student moved to GPU for training")
    
    def _swap_to_teacher(self):
        """Move student to CPU and reload teacher for generation."""
        self.student = self.student.cpu()
        torch.cuda.empty_cache()
        # Teacher needs to be reloaded (was deleted)
        self._load_teacher()
    
    def _generate_qa_from_teacher(self, paper_chunks: List[str], 
                                   num_qa_per_chunk: int = 3) -> List[Dict]:
        """
        Generate Q&A pairs using the teacher model.
        
        For each chunk of paper text, the teacher generates questions
        and their answers.
        """
        self._load_teacher()
        qa_pairs = []
        
        prompt_template = (
            "Based on the following research text, generate {n} specific "
            "question-answer pairs that test understanding of the key concepts.\n\n"
            "Research text:\n{text}\n\n"
            "Generate exactly {n} Q&A pairs in this format:\n"
            "Q1: [question]\nA1: [detailed answer]\n"
        )
        
        logger.info(f"Generating Q&A from {len(paper_chunks)} chunks...")
        
        for i, chunk in enumerate(paper_chunks):
            if len(chunk.strip()) < 100:
                continue
            
            # Truncate long chunks
            chunk_text = chunk[:1500]
            
            prompt = prompt_template.format(n=num_qa_per_chunk, text=chunk_text)
            
            try:
                inputs = self.teacher_tokenizer(
                    prompt, return_tensors='pt', max_length=1024, truncation=True
                ).to(self.teacher_model.device)
                
                with torch.no_grad():
                    outputs = self.teacher_model.generate(
                        **inputs,
                        max_new_tokens=512,
                        temperature=0.7,
                        do_sample=True,
                        top_p=0.9,
                        pad_token_id=self.teacher_tokenizer.pad_token_id,
                    )
                
                generated_text = self.teacher_tokenizer.decode(
                    outputs[0][inputs['input_ids'].shape[1]:], 
                    skip_special_tokens=True
                )
                
                # Parse Q&A pairs from generated text
                parsed = self._parse_qa_text(generated_text, source_chunk=chunk_text)
                qa_pairs.extend(parsed)
                
            except Exception as e:
                logger.warning(f"Failed to generate Q&A for chunk {i}: {e}")
                continue
            
            if (i + 1) % 50 == 0:
                logger.info(f"  Generated {len(qa_pairs)} Q&A pairs from {i+1} chunks")
        
        logger.info(f"Total Q&A pairs generated: {len(qa_pairs)}")
        return qa_pairs
    
    def _parse_qa_text(self, text: str, source_chunk: str = "") -> List[Dict]:
        """Parse Q&A pairs from teacher-generated text."""
        import re
        pairs = []
        
        # Match patterns like Q1: ... A1: ...
        pattern = r'Q\d*[:.]?\s*(.*?)\s*A\d*[:.]?\s*(.*?)(?=Q\d*[:.]|$)'
        matches = re.findall(pattern, text, re.DOTALL)
        
        for q, a in matches:
            q = q.strip()
            a = a.strip()
            if len(q) > 10 and len(a) > 20:
                pairs.append({
                    'question': q,
                    'answer': a,
                    'source': source_chunk[:200],
                })
        
        # Fallback: if no Q/A pattern found, try to use the whole text
        if not pairs and len(text.strip()) > 50:
            pairs.append({
                'question': f"Explain the key concepts in: {source_chunk[:100]}...",
                'answer': text.strip(),
                'source': source_chunk[:200],
            })
        
        return pairs
    
    def _generate_questions_from_student(self, num_questions: int = 50) -> List[str]:
        """
        Generate new questions using the student model.
        
        This is the self-evolution component: ScholarFormer generates
        questions based on what it has learned, which the teacher then
        answers, creating new training data.
        """
        self.student.eval()
        questions = []
        
        prompts = [
            "Question about transformer architecture: ",
            "Question about attention mechanisms: ",
            "Question about language model training: ",
            "Question about research methodology: ",
            "Question about neural network optimization: ",
            "Question about natural language processing: ",
            "Question about fine-tuning techniques: ",
            "Question about knowledge distillation: ",
        ]
        
        # Tokenizer access
        tok = (self.student_tokenizer.tokenizer 
               if hasattr(self.student_tokenizer, 'tokenizer') 
               else self.student_tokenizer)
        
        for i in range(num_questions):
            prompt = prompts[i % len(prompts)]
            
            try:
                inputs = tok(prompt, return_tensors='pt')
                input_ids = inputs['input_ids'].to(self.device)
                
                with torch.no_grad():
                    generated = self.student.generate(
                        input_ids, max_new_tokens=64,
                        temperature=0.9, top_k=50
                    )
                
                question = tok.decode(generated[0], skip_special_tokens=True)
                
                # Clean up: extract just the question part
                if '?' in question:
                    question = question[:question.index('?') + 1]
                
                if len(question) > 20:
                    questions.append(question)
                    
            except Exception as e:
                logger.warning(f"Failed to generate question {i}: {e}")
                continue
        
        logger.info(f"Student generated {len(questions)} questions")
        return questions
    
    def _train_student_on_qa(self, qa_pairs: List[Dict], 
                              num_epochs: int = 2,
                              learning_rate: float = 5e-5) -> Dict:
        """Train the student model on Q&A pairs."""
        dataset = DistillationDataset(
            qa_pairs, self.student_tokenizer, max_length=512
        )
        
        if len(dataset) == 0:
            logger.warning("No valid Q&A samples for training!")
            return {'loss': float('inf')}
        
        dataloader = DataLoader(
            dataset, batch_size=4, shuffle=True,
            collate_fn=distillation_collate_fn,
            num_workers=0, pin_memory=True
        )
        
        optimizer = torch.optim.AdamW(
            self.student.parameters(), lr=learning_rate,
            weight_decay=0.01, betas=(0.9, 0.95)
        )
        
        scaler = torch.cuda.amp.GradScaler()
        self.student.train()
        
        total_loss = 0
        total_steps = 0
        
        for epoch in range(num_epochs):
            epoch_loss = 0
            for batch in dataloader:
                input_ids = batch['input_ids'].to(self.device)
                labels = batch['labels'].to(self.device)
                
                with torch.cuda.amp.autocast():
                    outputs = self.student(input_ids, labels=labels)
                    loss = outputs['loss']
                
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(self.student.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad()
                
                epoch_loss += loss.item()
                total_steps += 1
            
            avg_loss = epoch_loss / max(1, len(dataloader))
            total_loss += avg_loss
            logger.info(f"  Distillation epoch {epoch+1}/{num_epochs}: loss={avg_loss:.4f}")
        
        return {
            'avg_loss': total_loss / num_epochs,
            'steps': total_steps,
            'num_samples': len(dataset),
        }
    
    # ==========================================================================
    # Main Distillation Loop
    # ==========================================================================
    
    def distill(self, paper_chunks: List[str], num_cycles: int = 5,
                qa_per_chunk: int = 3, student_questions_per_cycle: int = 30,
                training_epochs_per_cycle: int = 2) -> Dict:
        """
        Run the full cross-model self-distillation loop.
        
        Args:
            paper_chunks: List of paper text chunks
            num_cycles: Number of distillation cycles
            qa_per_chunk: Q&A pairs to generate per chunk
            student_questions_per_cycle: Questions the student generates per cycle
            training_epochs_per_cycle: Training epochs per distillation cycle
        
        Returns:
            Dict with distillation results and metrics
        """
        logger.info("=" * 60)
        logger.info("🧬 CROSS-MODEL SELF-DISTILLATION")
        logger.info(f"   Teacher: Phi-3 (3.8B) → Student: ScholarFormer (122M)")
        logger.info(f"   Cycles: {num_cycles}")
        logger.info("=" * 60)
        
        start_time = time.time()
        
        for cycle in range(num_cycles):
            cycle_start = time.time()
            
            logger.info(f"\n{'─'*40}")
            logger.info(f"🔄 DISTILLATION CYCLE {cycle + 1}/{num_cycles}")
            logger.info(f"{'─'*40}")
            
            # Step 1: Teacher generates Q&A pairs
            if cycle == 0:
                # First cycle: generate from paper chunks (teacher loads automatically)
                qa_pairs = self._generate_qa_from_teacher(
                    paper_chunks[:100],  # Limit to first 100 chunks per cycle
                    num_qa_per_chunk=qa_per_chunk
                )
            else:
                # Swap teacher back to GPU for generation
                self._swap_to_teacher()
                
                # Subsequent cycles: augment with student-generated questions
                # (student generates on CPU, which is slower but avoids VRAM issues)
                student_questions = self._generate_questions_from_student(
                    num_questions=student_questions_per_cycle
                )
                
                # Teacher answers student's questions
                new_qa = self._teacher_answers_questions(student_questions)
                
                # Also sample new chunks
                chunk_start = (cycle * 50) % len(paper_chunks)
                new_chunk_qa = self._generate_qa_from_teacher(
                    paper_chunks[chunk_start:chunk_start + 50],
                    num_qa_per_chunk=qa_per_chunk
                )
                
                qa_pairs = new_qa + new_chunk_qa
            
            if not qa_pairs:
                logger.warning(f"No Q&A pairs generated in cycle {cycle + 1}, skipping")
                continue
            
            self.all_qa_pairs.extend(qa_pairs)
            
            # Step 2: Swap student to GPU and train on Q&A pairs
            self._swap_to_student()
            logger.info(f"Training student on {len(qa_pairs)} Q&A pairs...")
            train_result = self._train_student_on_qa(
                qa_pairs, 
                num_epochs=training_epochs_per_cycle,
                learning_rate=5e-5 * (0.9 ** cycle)  # Decay LR each cycle
            )
            
            cycle_time = time.time() - cycle_start
            
            cycle_metrics = {
                'cycle': cycle + 1,
                'num_qa_pairs': len(qa_pairs),
                'total_qa_accumulated': len(self.all_qa_pairs),
                'training_loss': train_result.get('avg_loss', None),
                'time_seconds': cycle_time,
            }
            self.cycle_history.append(cycle_metrics)
            
            logger.info(f"\n  📊 Cycle {cycle + 1} results:")
            logger.info(f"     Q&A pairs: {len(qa_pairs)}")
            logger.info(f"     Training loss: {train_result.get('avg_loss', 'N/A'):.4f}")
            logger.info(f"     Time: {cycle_time:.1f}s")
            
            # Save cycle checkpoint
            self._save_cycle(cycle + 1)
        
        total_time = time.time() - start_time
        
        result = {
            'num_cycles': num_cycles,
            'total_qa_pairs': len(self.all_qa_pairs),
            'total_time_seconds': total_time,
            'total_time_human': f"{total_time / 3600:.1f} hours",
            'cycle_history': self.cycle_history,
        }
        
        # Save final results
        self._save_results(result)
        
        logger.info(f"\n{'='*60}")
        logger.info(f"✅ DISTILLATION COMPLETE!")
        logger.info(f"   Total cycles: {num_cycles}")
        logger.info(f"   Total Q&A pairs: {len(self.all_qa_pairs):,}")
        logger.info(f"   Total time: {total_time/3600:.1f} hours")
        logger.info(f"{'='*60}")
        
        return result
    
    def _teacher_answers_questions(self, questions: List[str]) -> List[Dict]:
        """Have the teacher model answer student-generated questions."""
        self._load_teacher()
        qa_pairs = []
        
        for q in questions:
            prompt = (
                f"Answer the following research question in detail:\n\n"
                f"Question: {q}\n\n"
                f"Answer:"
            )
            
            try:
                inputs = self.teacher_tokenizer(
                    prompt, return_tensors='pt', max_length=512, truncation=True
                ).to(self.teacher_model.device)
                
                with torch.no_grad():
                    outputs = self.teacher_model.generate(
                        **inputs, max_new_tokens=256,
                        temperature=0.7, do_sample=True, top_p=0.9,
                        pad_token_id=self.teacher_tokenizer.pad_token_id,
                    )
                
                answer = self.teacher_tokenizer.decode(
                    outputs[0][inputs['input_ids'].shape[1]:],
                    skip_special_tokens=True
                )
                
                if len(answer.strip()) > 20:
                    qa_pairs.append({
                        'question': q,
                        'answer': answer.strip(),
                        'source': 'student_generated',
                    })
            except Exception as e:
                logger.warning(f"Teacher failed to answer: {e}")
                continue
        
        logger.info(f"Teacher answered {len(qa_pairs)}/{len(questions)} questions")
        return qa_pairs
    
    def _save_cycle(self, cycle_num: int):
        """Save distillation cycle checkpoint."""
        path = os.path.join(self.output_dir, f'cycle_{cycle_num}')
        os.makedirs(path, exist_ok=True)
        
        # Save student weights
        torch.save({
            'model_state_dict': self.student.state_dict(),
            'cycle': cycle_num,
            'timestamp': datetime.now().isoformat(),
        }, os.path.join(path, 'student.pt'))
        
        # Save Q&A pairs
        with open(os.path.join(path, 'qa_pairs.json'), 'w', encoding='utf-8') as f:
            json.dump(self.all_qa_pairs, f, indent=2, ensure_ascii=False)
        
        logger.info(f"💾 Cycle {cycle_num} saved to {path}")
    
    def _save_results(self, results: Dict):
        """Save final distillation results."""
        with open(os.path.join(self.output_dir, 'distillation_results.json'), 'w') as f:
            json.dump(results, f, indent=2, default=str)
        
        with open(os.path.join(self.output_dir, 'all_qa_pairs.json'), 'w', encoding='utf-8') as f:
            json.dump(self.all_qa_pairs, f, indent=2, ensure_ascii=False)
        
        logger.info(f"Results saved to {self.output_dir}")
